# Project Name
spring.application.name=foodsystem

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3307/food_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=foodorderingsystemsecretkey1234567890abcdef
jwt.expiration=86400000